#Definimos el tipo de base de datos 
quarkus.datasource.db-kind=postgresql
#Usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
#password del usuario de conexion
quarkus.datasource.password=1234562
#Url de conection a la base de datos
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pa2db
#En que esenario se va a sincronizar la base de datos, en este caso se actualiza cada vez que se inicia la aplicacion
quarkus.hibernate-orm.database.generation=update
#Cada que hacemos una consulta a la base de datos se va a mostrar en consola el sql que se esta ejecutando
quarkus.hibernate-orm.log.sql=true